Fix conversion of hoomd box to vmd
mphowardlab/gsd-vmd pull request #9
Opened 2021-09-25 02:21 UTC by ksil

I think the vmd lattice constants (if A, B, and C are indeed lattice constants) should also involve the tilt factors, consistent with HOOMD's definition: https://hoomd-blue.readthedocs.io/en/stable/box.html. (I noticed in some shear simulations that the box looked too small in the gradient direction!)

2021-09-25 19:56 UTC, mphoward requested changes
Thanks for the PR! I agree that the original code is incorrect because the (a,b,c) parameters should be the length of the lattice vectors:

> Format of the unit cell parameters cell. When -vmd is used, a parameter set must be a list of the VMD unitcell parameters a, b, c (i.e. the side lengths of the unit cell) and optionally alpha, beta and gamma (the angles of the unit cell) for non-orthorhombic unitcells. When -namd is used, a parameter set must contain the three unit cell vectors A, B and C (the 3D-vectors of the unitcell sides) (default:-vmd).

(https://www.ks.uiuc.edu/Research/vmd/plugins/pbctools/)

However, I have a small request to change the way this is applied to ensure the values for orthorhombic boxes are still read exactly. Please make the suggested change, and I think this should be good to merge!

2021-09-25 19:56 UTC, mphoward commented on gsdplugin.c
> +            ts->A = box[0]; ts->B = (float)norm1*box[1]; ts->C = (float)norm2*box[2];
To make sure orthorhombic boxes still get their sizes set exactly, please put this code back in the `if` branch below and include these new lines there:
```
ts->A = box[0];
ts->B = (float)(norm1*box[1]);
ts->C = (float)(norm2*box[2]);
```
Then, also add the original line to the `else` branch where the angles are also set exactly:
```
ts->A = box[0]; ts->B = box[1]; ts->C = box[2];
```

2021-09-26 20:26 UTC, ksil reviewed
Sounds good!

2021-09-27 18:07 UTC, merged

2021-09-27 18:13 UTC, mphoward commented
Thanks again!